export const nationalityMap: { [key: string]: string } = {
  American: '🇺🇸',
  Canadian: '🇨🇦',
  British: '🇬🇧',
  German: '🇩🇪',
  French: '🇫🇷',
  Spanish: '🇪🇸',
  Italian: '🇮🇹',
  Mexican: '🇲🇽',
  Australian: '🇦🇺',
  Brazilian: '🇧🇷',
  Japanese: '🇯🇵',
  Chinese: '🇨🇳',
  Indian: '🇮🇳',
  Russian: '🇷🇺',
  'South Korean': '🇰🇷',
  'Saudi Arabian': '🇸🇦',
  Turkish: '🇹🇷',
  Dutch: '🇳🇱',
  Swedish: '🇸🇪',
  Norwegian: '🇳🇴',
  Danish: '🇩🇰',
  Finnish: '🇫🇮',
  Greek: '🇬🇷',
  Polish: '🇵🇱',
  Portuguese: '🇵🇹',
  Argentine: '🇦🇷',
  Chilean: '🇨🇱',
  Colombian: '🇨🇴',
  Peruvian: '🇵🇪',
  Egyptian: '🇪🇬',
  'South African': '🇿🇦',
  Nigerian: '🇳🇬',
  Kenyan: '🇰🇪',
  'New Zealand': '🇳🇿',
  Indonesian: '🇮🇩',
  Malaysian: '🇲🇾',
  Thai: '🇹🇭',
  Vietnamese: '🇻🇳',
  Philippine: '🇵🇭',
  Singaporean: '🇸🇬',
  Pakistani: '🇵🇰',
  Bangladeshi: '🇧🇩',
  Israeli: '🇮🇱',
  Ukrainian: '🇺🇦',
  Iranian: '🇮🇷',
  Iraqi: '🇮🇶',
  Jordanian: '🇯🇴',
  Lebanese: '🇱🇧',
  Syrian: '🇸🇾',
  Afghan: '🇦🇫',
  'Sri Lankan': '🇱🇰',
  Nepali: '🇳🇵',
  Maldivian: '🇲🇻',
  Kazakh: '🇰🇿',
  Uzbek: '🇺🇿',
  Tajik: '🇹🇯',
  Kyrgyz: '🇰🇬',
  Turkmen: '🇹🇲',
  Armenian: '🇦🇲',
  Georgian: '🇬🇪',
  Moldovan: '🇲🇩',
  Albanian: '🇦🇱',
  Kosovar: '🇽🇰',
  Montenegrin: '🇲🇪',
  Bosnian: '🇧🇦',
  Serbian: '🇷🇸',
  Croatian: '🇭🇷',
  Slovenian: '🇸🇮',
  'North Macedonian': '🇲🇰',
  Belarusian: '🇧🇾',
  Latvian: '🇱🇻',
  Lithuanian: '🇱🇹',
  Estonian: '🇪🇪',
  Bulgaria: '🇧🇬',
  Romanian: '🇷🇴',
  Hungarian: '🇭🇺',
  Czech: '🇨🇿',
  Slovakian: '🇸🇰',
  Malawian: '🇲🇼',
  Zambian: '🇿🇲',
  Ugandan: '🇺🇬',
  Tanzanian: '🇹🇿',
  Rwandan: '🇷🇼',
  Botswanan: '🇧🇼',
  Namibian: '🇳🇦',
};

export const genderMap: { [key: string]: string } = {
  Male: '👨', // Man icon
  Female: '👩', // Woman icon
  'LGBTQ+': '🏳️‍🌈', // LGBTQ+ flag
};
